apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - resources.yaml

commonLabels:
  app.kubernetes.io/name: spring-ai-starter
  app.kubernetes.io/managed-by: kustomize
